#!/usr/bin/env bash
source ./scripts/helpers/debug.sh
source ./scripts/helpers/init_clasp.sh
source ./scripts/helpers/secrets.sh
export $(egrep -v '^#' .env | xargs)
turn_on_debugging

usage() {
  cat <<-USAGE
$(basename $0) [function_name]
Runs a GAS project function.

USAGE
}

push_to_clasp() {
  docker-compose run --rm clasp push
}

run_function_with_clasp() {
  docker-compose run --rm clasp run $1
}


if [ "$1" == '--help' ]
then
  usage
  exit 0
fi

initialize_clasp &&
  push_to_clasp &&
  set_project_secrets &&
  run_function_with_clasp "$1"

turn_off_debugging
